### ISSUE TITLE
[BUG] K8s Cluster Monitoring does not get configured

### ISSUE THREAD

**Issue by joshlange-dt** [Dynatrace/ace-box#119]
Using the latest dev build. Sprint version .232. In the k8s dashboard you can see the ACE-BOX cluster but the config does not have the api url set, bearer token set, and optional AG group. 

Containerized AG is online and healthy, just the k8s cluster config does not get created. 

ENV: Azure terraform build

**Comment by kristofre** [comment]
Seems that there was a regression due to the change we made in how we deploy the OA Operator. Issue has been identified and will be resolved soon. Thanks @joshlange-dt for flagging!
