### ISSUE TITLE
[BUG] Quality gates ace-demo broken

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#150]
Ace demo is broken for keptn and quality gates, the labels are missing for the SLI. The expected label is DT_APPLICATION_RELEASE_VERSION. The application under Dynatrace is  DT_RELEASE_VERSION. Which one should be fixed? the SLI file? or the Dynatrace env tags?

**Comment by tobigremmer-dt** [comment]
Probably unrelated to mentioned label. DT_RELEASE_VERSION is mapped to DT_APPLICATION_RELEASE_VERSION in the background.

Nevertheless, use case is broken and requires investigation. Last successful AppSec run on January 19, last successful Demo run on January 13.

**Comment by drqc** [comment]
So it works when using this expression 
`metricSelector=builtin:service.response.time:merge("dt.entity.service"):percentile(95)&entitySelector=tag(app:simplenodeservice,environment:staging),type(SERVICE)`

2 Fixes done here: "dt.entity.service" without scape forward slashes and using the simple tags. One of the new tags might not be available but I will have to test to check which one is failing

**Comment by drqc** [comment]
more info on this bug, running a syntax like `merge("\dt.entity.service\")` (with escaping qoutes) is not allowed for the dynatrace API as it has been deprecated but the required syntax for the dynatrace service.

**Comment by drqc** [comment]
I have fixed the sli definition and updated the pipeline labels. It works now, I have followed the slack chat about the tags being updated to the latest version
```1) There was some renaming of the variables some time ago but the agent still supports the old variable names.
Therefore, you can use either one (depending on the agent version).
Version:        DT_APPLICATION_RELEASE_VERSION, DT_RELEASE_VERSION
Build version:  DT_APPLICATION_BUILD_VERSION, DT_RELEASE_BUILD_VERSION
Name:           DT_APPLICATION_NAME, DT_RELEASE_PRODUCT
Environment:    DT_APPLICATION_ENVIRONMENT, DT_RELEASE_STAGE
Before sprint 220 auto tags were generated for those variables.
Since 220 the variables are stored in the agent properties .```
