### ISSUE TITLE
[BUG] Azure ACE-BOX provisioning failed

### ISSUE THREAD

**Issue by lplichart** [Dynatrace/ace-box#180]
**Describe the bug**
Terraform provisioning of the ace-box on Azure fails, see output below:

module.provisioner.null_resource.provisioner_ace_install (remote-exec): TASK [dt-oneagent : Create Dynatrace namespace] ********************************
module.provisioner.null_resource.provisioner_ace_install (remote-exec): An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ModuleNotFoundError: No module named 'openshift'
module.provisioner.null_resource.provisioner_ace_install (remote-exec): fatal: [localhost]: FAILED! => {"changed": false, "error": "No module named 'openshift'", "msg": "Failed to import the required Python library (openshift) on ace-box's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

module.provisioner.null_resource.provisioner_ace_install (remote-exec): PLAY RECAP *********************************************************************
module.provisioner.null_resource.provisioner_ace_install (remote-exec): localhost                  : ok=22   changed=17   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

module.provisioner.null_resource.provisioner_ace_install (remote-exec): Traceback (most recent call last):
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/local/bin/ace", line 454, in <module>
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     ace(auto_envvar_prefix='ACE')
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1128, in __call__
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     return self.main(*args, **kwargs)
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1053, in main
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     rv = self.invoke(ctx)
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1659, in invoke
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     return _process_result(sub_ctx.command.invoke(sub_ctx))
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1395, in invoke
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     return ctx.invoke(self.callback, **ctx.params)
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 754, in invoke
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     return __callback(*args, **kwargs)
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/local/bin/ace", line 440, in enable
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     check=True,
module.provisioner.null_resource.provisioner_ace_install (remote-exec):   File "/usr/lib/python3.6/subprocess.py", line 438, in run
module.provisioner.null_resource.provisioner_ace_install (remote-exec):     output=stdout, stderr=stderr)
module.provisioner.null_resource.provisioner_ace_install (remote-exec): subprocess.CalledProcessError: Command 'ansible-playbook main-v2.yml --extra-vars "ace_box_user=ace" --tags "demo_default"' returned non-zero exit status 2.
╷
│ Error: remote-exec provisioner error
│ 
│   with module.provisioner.null_resource.provisioner_ace_install,
│   on ../modules/ace-box-provisioner/main.tf line 88, in resource "null_resource" "provisioner_ace_install":
│   88:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_848844862.sh": Process exited with status 1

**To Reproduce**
Steps to reproduce the behavior: Error occurs when terraform apply command is executed.  

**Expected behavior**
The terraform should complete normally

**Screenshots**
N/A

**Desktop (please complete the following information):**
terraform was started from an Azure VM (Ubuntu 20.04 LTS).  Azure environment used is the Sales-Engineering/EMEA subscription

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by kristofre** [comment]
This also affects AWS, but not google.

It seems the root cause is that for google we are using Ubuntu 20 images, but for Azure/AWS are still on 18.
Will investigate more and fix if appropriate
