### ISSUE TITLE
[BUG] Provisioner fails on Windows

### ISSUE THREAD

**Issue by tannerKnue** [Dynatrace/ace-box#181]
**Describe the bug**
This might be a windows specific problem. The bug occurs when applying the terraform configurations in the 'main.tf' file. More specifically, when the 'main.tf' file attempts to run the 'provisioner_ace_prepare' part of the code. The terminal outputs two lines: 

module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): Error: No such option: --force
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):  Did you mean --force?

The configurations were manually configured to solve the problem. 

**To Reproduce**
1. In the terminal enter 'terraform apply'
2. Enter yes when prompted 'yes'
3. The error occurs when the 'main.tf' file attempts to execute the  'provisioner_ace_prepare' part of the code.

**Expected behavior**
The configurations to be configured both default and custom.

**Screenshots**
Below is what the terminal outputs in the bug section:

module.provisioner.null_resource.provisioner_ace_prepare: Creating...
module.provisioner.null_resource.provisioner_ace_prepare: Provisioning with 'remote-exec'...
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): Connecting to remote host via SSH...
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   Host: 35.184.40.74
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   User: ace
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   Password: false
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   Private key: true
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   Certificate: false
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   SSH Agent: false
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   Checking Host Key: false
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):   Target Platform: unix
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): Connected!
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): sudo:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : command not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 3:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 4:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 5:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 6:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 7:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 8:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 9:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): /tmp/terraform_1296911407.sh: 10:
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): : not found
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): Usage: ace prepare [OPTIONS]
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): Try 'ace prepare --help' for help.

╷
│ Error: remote-exec provisioner error
│
│   with module.provisioner.null_resource.provisioner_ace_prepare,
│   on ..\modules\ace-box-provisioner\main.tf line 60, in resource "null_resource" "provisioner_ace_prepare":
│   60:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1296911407.sh": Process exited with status 2
╵
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec): Error: No such option: --force
module.provisioner.null_resource.provisioner_ace_prepare (remote-exec):  Did you mean --force?

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Microsoft Edge]
 - Version [10.0.22]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tannerKnue** [comment]
terraform version: 1.2.2

**Comment by tobigremmer-dt** [comment]
This seems to be related to backslashes in the Terraform provisioner's inline script:

```
provisioner "remote-exec" {
    inline = [
      <<EOF
sudo ACE_ANSIBLE_WORKDIR=/home/${local.user}/ansible/ \
ACE_BOX_USER=${local.user} \
ACE_INGRESS_DOMAIN=${local.ingress_domain} \
ACE_INGRESS_PROTOCOL=${local.ingress_protocol} \
ACE_DT_TENANT=${local.dt_tenant} \
ACE_DT_API_TOKEN=${local.dt_api_token} \
ACE_DT_PAAS_TOKEN=${local.dt_paas_token} \
ACE_CA_TENANT=${local.ca_tenant} \
ACE_CA_API_TOKEN=${local.ca_api_token} \
ace prepare --force
      EOF
    ]
  }
```
