### ISSUE TITLE
[FEATURE] Validation of API tokens early on in provisioning

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#199]
**Is your feature request related to a problem? Please describe.**
Sometimes tokens are used with insufficient scope/typo/... which only gets detected while running the use cases. At this point it is almost better to just re-provision instead of fixing.

**Describe the solution you'd like**
Have a step early on that verifies endpoint/tokens and provides a clear message and failure.

**Comment by tobigremmer-dt** [comment]
Resolved by #378
