### ISSUE TITLE
[FEATURE] The ACE Dashboard "Use Cases" section should be more generic

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#201]
**Is your feature request related to a problem? Please describe.**
The "Use Cases" section would be great to provide additional information on the specifically created ACE-BOX.
At the moment, the dashboard looks for variables (e.g. GitLab user name, password, ...) to define what to show there.
This limits the use.

**Describe the solution you'd like**
Offer a generic approach, perhaps leveraging a config map, to display data in the use cases section

**Comment by tobigremmer-dt** [comment]
Also applies to links, etc. In general all elements should be shown only if they are relevant.

Possible solution:
- Dashboard role provides task to generate configmap
- Configmap contains all information to show ACE Box links, external links, credentials, previews, etc... for use case
- Use Case roles then calls configmap task of Dashboard role

**Comment by kristofre** [comment]
An idea could be to truly separate use case from tooling. Main dashboard page contains tooling overview and in the bottom a list of all use cases like today. Clicking on a use case opens a separate page that has a generic deployment preview + link to the use case documentation (currently in gitea/gitlab but in the future a dedicated component). Deployment preview as it is today goes away.
