### ISSUE TITLE
[BUG] Terraform broken on M1 based Macs

### ISSUE THREAD

**Issue by StefanPostma** [Dynatrace/ace-box#203]
**Describe the bug**
Launching Terraform init for AWS terraform will fail on M1 with error:
Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/random v3.0.0 does not have a
│ package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.

Fix seems to be update versions.tf : Random to latest version 3.3.2 

Checking if rest of the process will proceed with newer version.

**Desktop (please complete the following information):**
 - OS: 12.4 Mac OS M1

**Additional context**
Will update ticket if update does not cause other issues.

**Comment by tobigremmer-dt** [comment]
<del>Should have been fixed with [v1.11.2](https://github.com/Dynatrace/ace-box/releases/tag/v1.11.2) . Can you please check whether you're using the latest ACE-Box version, @StefanPostma ?</del>

Nevermind, just saw the fix was not implemented for AWS.

**Comment by StefanPostma** [comment]
confirmed if you change registry.terraform.io/hashicorp/random to version 3.3.2 its works for the M1 Mac

**Comment by kristofre** [comment]
> 

@StefanPostma are you able to implement a fix and create a Pull Request?

**Comment by StefanPostma** [comment]
sure, i will look into it after the weekend :)
