### ISSUE TITLE
[FEATURE] Ansible role for deploying EasyTravel

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#210]
**Is your feature request related to a problem? Please describe.**
Right now, app deployment often happens as part of the use case (e.g. simplenode service for demos, unguard for appsec hot, easytravel for IM HOT). As part of building use cases, users of the acebox platform might want demo apps automatically deployed and not having to take care of it separately.

**Describe the solution you'd like**
At least the following ansible roles:
- EasyTravel

Other roles, like use case roles, can then reuse these

**Comment by tobigremmer-dt** [comment]
To clarify: EasyTravel on Kubernetes
