### ISSUE TITLE
[FEATURE] Rename `demo_default`, `demo_appsec` and `demo_gitlab` use cases and configurations in jenkins

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#213]
**Is your feature request related to a problem? Please describe.**
The names `demo_default` and `demo_appsec` are not very descriptive and therefor can be confusing to users. Similarly, when going into Jenkins, the folders don't say much about what it contains.

![image](https://user-images.githubusercontent.com/9797800/181181172-4002bb94-4c5f-46bf-87c1-a368f4576d71.png)

**Describe the solution you'd like**
I suggest a renaming:
- `demo_default` to become `demo_quality_gates_jenkins`
- `demo_appsec` to become `demo_security_gates`
- `demo_gitlab` to become `demo_quality_gates_gitlab` to be in line with the others

At the same time, the folders in jenkins should follow suit as well where applicable (demo_default and demo_appsec only).
Documentation should be updated as well

**Comment by tobigremmer-dt** [comment]
Update: `demo_appsec` shall be named `demo_security_gates_jenkins`
