### ISSUE TITLE
[FEATURE] Generic Use Case guides

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#215]
**Is your feature request related to a problem? Please describe.**
Right now the use case documentation is stored in the gitea/gitlab repo, which makes it sometimes hard to find and is not ideal for following along. 

**Describe the solution you'd like**
Introduce Google Code Labs for our labs and host it on the ace box: https://github.com/googlecodelabs/tools

**Comment by tobigremmer-dt** [comment]
There's a bunch of tools that allow to create more generic guides (https://docusaurus.io is another example). Regardless of the specific tool, ideally DTU lab guides can be repurposed - OR - migrated to a format the tool understands.
