### ISSUE TITLE
Deployment Preview not working for Gitlab Images

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#235]
Using this environment: http://dashboard.acebox-kr.ace-innovation.info/ to test Gitlab based deployments.  Preview Page not showing the simplenodeservice.

![image](https://user-images.githubusercontent.com/52331581/182222660-2ad7ecf3-dd23-4d30-a89a-18a4d75059da.png)

**Comment by kristofre** [comment]
Thanks for logging. This is related to bigger issue #201

**Comment by kristofre** [comment]
This also impacts the demo_default demo

**Comment by tobigremmer-dt** [comment]
Fixed as part of #201
