### ISSUE TITLE
[FEATURE] ACE-Bot ChatOps

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#240]
**Is your feature request related to a problem? Please describe.**
A chat bot shall be investigated and implemented, that allows provisioning an ACE-Box through a chat interface.

Requirements:
- ACE-Box deployment and use case provisioning needs to be as hands-off as possible
- All default use cases can be provisioned
- External use cases can be provisioned
- ACE-Box shall be destroyed after a configurable amount of time
- AWS, Azure, GCP account metadata shall be provided dynamically so it's possible to spin up ACE-Boxes  for different (e.g. Slack) channels in different cloud providers and/or accounts
- Cloud resources shall be tagged with requester

**Comment by kristofre** [comment]
Deprecated by Aether
