### ISSUE TITLE
[FEATURE] Align Jenkins parameters with best practices

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#254]
**Is your feature request related to a problem? Please describe.**
Currently, Jenkins pipeline parameters are used that don't comply to any best practices (e.g. APP_NAME, ART_VERSION, ...). These parameters shall be aligned with best practice according to:
- https://www.dynatrace.com/support/help/how-to-use-dynatrace/cloud-automation/release-monitoring/version-detection-strategies
- https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by zeroho** [comment]
在 2023年5月9日週二 21:58，tobigremmer-dt ***@***.***> 寫道：
