### ISSUE TITLE
[FEATURE] Run demo happy flows upon provisioning

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#258]
**Is your feature request related to a problem? Please describe.**
Once an ACE-Box is provisioned, a use case happy flow shall be triggered. This allows for:
- Data being present on the ACE-Box opposed to starting from scratch (e.g. evaluations, ...) at the time of an actual demo
- New k8s workloads being known to Dynatrace ahead of actual demo

**Comment by kristofre** [comment]
I like the idea

This already happens in gitlab by default.
In Jenkins, the easiest is to change the pipeline to trigger upon changes in the main branch. That means it will trigger automatically as well when being added.
