### ISSUE TITLE
[BUG]  Step by Step Instructions Not Accessible

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#266]
When trying to access step by step instructions, getting a Page Not Found error from Gitea in response.  This is happening in the Demo live and Demo Dev.  It does say it could be permissions related, however would not expect to be limited from this content.

**Comment by tobigremmer-dt** [comment]
Hi @jpc-dt , the repositories our instructions are in require authentication. Credentials can be found on the ACE-Box dashboard.

(Additional note: The link to the Jenkins QG demo docs is indeed broken but will be fixed with #273 )
