### ISSUE TITLE
[BUG] Demo Live Quality Gates (default demo) Not Returning SLI Data

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#267]
![image](https://user-images.githubusercontent.com/52331581/183532395-1b772a51-35b9-4ceb-b7a6-78e8c0d83c86.png)

![image](https://user-images.githubusercontent.com/52331581/183532493-1e046c02-003c-470f-bbb9-f80989a56c32.png)

**Comment by kristofre** [comment]
Hi @jpc-dt thanks for flagging. Did you do any further trouble shooting? Do we have data in Dynatrace?

**Comment by jpc-dt** [comment]
I did not do any further troubleshooting @kristofre.

**Comment by jpc-dt** [comment]
I am seeing request data in Dynatrace after running the test, including the request attributes.

**Comment by kristofre** [comment]
Redeployed demo-live with latest version seems all good now
