### ISSUE TITLE
[BUG] Demo Live Jenkins AppSec QG is not finding a vulnerability

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#271]
I'm running build 5 using the Jenkins app sec pipelines and there is no vulnerability being found in the Demo Live environment.

![image](https://user-images.githubusercontent.com/52331581/184387738-d6ff3304-e56d-4631-847b-194b7eeca673.png)

**Comment by kristofre** [comment]
Hi @jpc-dt , can you verify the environment? Demo Live has not had the security gates project triggered

**Comment by jpc-dt** [comment]
Sorry @kristofre , It was in Demo Dev.  I am going to run some appsec in Demo Live now.  Will update for any similarities/differences.

**Comment by kristofre** [comment]
@jpc-dt rookie error on my behalf... I linked the demo-dev instance to a brand new SaaS DT instance which did not have AppSec enabled. Easily checked by opening the Third Party Vulnerabilities page within the DT Tenant. Running a new pipeline now

**Comment by kristofre** [comment]
![image](https://user-images.githubusercontent.com/9797800/185050965-9d7e49d5-dbe6-4406-b30f-a82df01aefeb.png)
Resolved by enabling AppSec license on DT tenant
