### ISSUE TITLE
[BUG] Demo-Live Jenkins Quality Gates not receiving data points

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#281]
![image](https://user-images.githubusercontent.com/52331581/187278518-7af8876c-c989-46f8-b34c-8c9c9c776d2f.png)

**Comment by jpc-dt** [comment]
Similar behavior is happening on the Jenkins App Sec Quality Gates.  The vulnerabilities are ok, but these similar metrics are not producing results.

**Comment by kristofre** [comment]
The license expired on the Dynatrace instance 🤦
