### ISSUE TITLE
[FEATURE] Assess multi instance support

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#287]
**Is your feature request related to a problem? Please describe.**
Currently, only one ACE-Box can ever run at it's own. All services, etc. are named the same. Multiple instances would collide e.g. in Dynatrace.

~~There shall be an option where multiple instances can be deployed simultaneously.~~

Multi instance support is currently implemented as a one-off solution in https://github.com/Dynatrace/ace-box/tree/t-cloud-summit . It shall be assessed if all or some of the features shall be included in the main code.

**Comment by eemrdog** [comment]
For multi-instance support, we can work with DTU as they can create multiple Ace-box instances. Ace-box supports the single instance
