### ISSUE TITLE
[FEATURE] Upgrade Gitea helm chart version to a newer

### ISSUE THREAD

**Issue by eemrdog** [Dynatrace/ace-box#316]
**Is your feature request related to a problem? Please describe.**
The initial request was to solve a security bug of a gitea version by upgrading it to a higher version than 1.16.7.
It was solved with this issue (https://github.com/Dynatrace/ace-box/issues/313)

**Describe the solution you'd like**
Gitea container image was upgraded to 1.17.2 version with an older helm chart version of 4.1.1. in the resolved issue above.
Upgrade Gitea helm chart version to a compatible version of the newer gitea images.

**Comment by tobigremmer-dt** [comment]
Resolved with #552
