### ISSUE TITLE
[FEATURE] Allow password login to ace-box VM

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#326]
**Is your feature request related to a problem? Please describe.**
At the moment only login by KEY file is possible.
For certain use cases (like auto remediation that needs to log in to the VM) a password login will be easier to work with.

**Describe the solution you'd like**
Introduce a new variable, e.g. `ace_box_password` to the ace cli.
When set (so not empty), set that as the `ace_box_user` user's password and allow login like this:

```
echo {{ ace_box_user }}:{{ ace_box_password }} | chpasswd
sed -i "s|^PasswordAuthentication no.*|PasswordAuthentication yes|g" /etc/ssh/sshd_config
systemctl restart ssh
```

**Comment by tobigremmer-dt** [comment]
Discussed today: Kristof is exploring options to create a dedicated SSH key pair for the use case. The private key is provided to AWX, public key added to the host.
