### ISSUE TITLE
[FEATURE] Allow extra ports to be opened on ace-box

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#327]
**Is your feature request related to a problem? Please describe.**
Certain use cases require extra ports to be opened.
Example: easytravel classic does not leverage the ingress controller and needs at least 2 extra ports.
This should be possible through an optional terraform parameter.

**Describe the solution you'd like**
Introduce a new optional variable with extra ports the user would like to see opened.

**Comment by tobigremmer-dt** [comment]
Duplicate of #300
