### ISSUE TITLE
[BUG] Cloud Automation 0.19.4, 0.19.5 incompatibility

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#348]
**Describe the bug**
There is no CLI matching the currently live CA version 0.19.4. Unfortunately, this prevents us from using CA for ACE-Box using for the time being.

Recommended workaround: The Keptn role can be used until CA+matching CLI version is published.

**Comment by tobigremmer-dt** [comment]
Same issue for 0.19.5

**Comment by kristofre** [comment]
Will also be an issue for 0.19.6. I asked the CA team if a 0.19.6 CLI can be released, they are looking into it

**Comment by kristofre** [comment]
Will be resolved with Keptn 1.0.0

**Comment by tobigremmer-dt** [comment]
~~Resolved by #407~~

Correction: Will be resolved as soon as Cloud Automation version (e.g. 1.0.0) is aligned with Keptn version. As of right now, a fallback to Keptn CLI 0.19.3 is required when deploying with CA.
