### ISSUE TITLE
[FEATURE] URL parameter cleansing

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#351]
**Is your feature request related to a problem? Please describe.**
Currently the ACE-Box is very strict about how URL variables are provided. E.g. adding a trailing slash to `dt_tenant_url` makes the provisioner fail. The ACE-Box shall cleanse URLs automatically, hence be more forgiving to manual user input variances.

**Comment by kristofre** [comment]
It should also verify both tokens and URLs for connectivity and deliver a clean error message
