### ISSUE TITLE
[FEATURE] Update unguard to latest version and adapt helm chart

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#352]
Unguard has seen new versions being released.
We need to adapt the helm chart - which has introduced new services - to deploy these services.

New services added:
- malicious-load-generator
- profile-service
- status-service

**Comment by anton-fre** [comment]
so I basically cloned the unguard version 0.6.1 into the app-unguard role. Still , app-unguard role does not seem to be used anywhere.

I still have to update the hot-appsec role (which uses unguard) to have the up to date helm charts.

**Comment by kristofre** [comment]
Hi Anton, unguard is not built from scratch when deploying it.
There is a helm chart in the `app-unguard` role. We need to make sure that the new version of the pre-built images get deployed and also update the helm chart to include the new services
