### ISSUE TITLE
[BUG] AWX not becoming healthy

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#376]
**Describe the bug**
For some reason, AWX is not properly starting up. For some reason, this only seems to be an issue when deploying the `demo_all` use case. It works perfectly fine for `demo_auto_remediation_ansible`.

Currently using a *n2-standard-16* instance on GCP with 16 vCPUs and 64 GB Memory. It doesn't seem to heal itself, as it's the same behavior after 15 mins of waiting.

Error message:

```
...
module.provisioner.null_resource.provisioner_ace_enable (remote-exec): FAILED - RETRYING: [localhost]: AWX - Wait for API to be up (1 retries left).
module.provisioner.null_resource.provisioner_ace_enable (remote-exec): fatal: [localhost]: FAILED! => {"attempts": 60, "changed": false, "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://10.152.183.3:80/api/v2/ping/"}
...
```

CURL doesn't work either:

```
$ curl http://10.152.183.3:80/api/v2/ping/
curl: (7) Failed to connect to 10.152.183.3 port 80: Connection refused
```

Only obvious error I could find was in the postgres pod:

```
...
2022-12-08 09:40:53.417 UTC [557] STATEMENT:  SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" WHERE ("django_migrations"."app" = 'main' AND NOT ("django_migrations"."name"::text LIKE '%squashed%')) ORDER BY "django_migrations"."id" DESC LIMIT 1
2022-12-08 09:40:53.419 UTC [557] ERROR:  relation "django_migrations" does not exist at character 124
...
```

**Comment by kristofre** [comment]
Spun up `demo_all` and can confirm the behaviour.
If I then delete the namespace `awx` and run `ace install awx` it will come up healthy.

**Comment by kristofre** [comment]
Troubleshooting yielded no real results.
The operator is showing some deployment time out in the logs.
Raised directly with ansible: https://github.com/ansible/awx-operator/issues/1149
