### ISSUE TITLE
[BUG] DTU env breaks with cloud init change

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#400]
cloud-init command has been added to the init.sh script but DTU reports that provisioning is hanging in that step. Related to this change https://github.com/Dynatrace/ace-box/pull/395
![image](https://user-images.githubusercontent.com/70604844/208174712-3e69466b-f95f-45ef-b69f-7f7ddcb4fd5f.png)

**Comment by dtu-engineering** [comment]
Adding some additional info from troubleshooting:

The last line in the cloud-init.log file is running the `/var/lib/cloud/instance/scripts/part-001` script which contains our EC2 userdata (Which runs cfn-init, which downloads and runs our custom DTU bootstrap script, which is what ultimately runs the init.sh Ace-Box setup script so it appears there is a circular dependency between the two..

`2022-12-16 19:54:25,045 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=False, capture=False)`

[12-16-cloud-init.log](https://github.com/Dynatrace/ace-box/files/10249494/12-16-cloud-init.log)

**Comment by kristofre** [comment]
@dtu-engineering for now we can build in a check to see if DTU is provisioning the ace box. Which env var can we check on to make that happen?

**Comment by dtu-engineering** [comment]
@kristofre Is it possible to check if /home/dtu_training dir exists? That is common among all of our templates and wouldn't require any changes on our side. But if you needed an env var to check I can export something like this. 

`export DTU_PROVISIONING=true`

**Comment by kristofre** [comment]
@dtu-engineering I would rather not use a folder that is based on the user name as somebody might (for some reason) use a user name with the same name. I see that you are setting `DTU_ENVIRONMENT_NAME`, can I check on the existence of that one?

**Comment by dtu-engineering** [comment]
@kristofre  Didn't catch that one that we set.  Yes that would work just fine.
