### ISSUE TITLE
[FEATURE] Update to keptn 1.0

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#401]
Todo:

- Update acebox to deploy keptn 1.0 
--- Keptn 1.0
--- Jmeter service (update url)
--- Dynatrace service for 1.0 test (sync with internal team)
--- Gitea provisioning service update (test if it works, Kristof has a branch with progress) https://github.com/keptn-sandbox/keptn-gitea-provisioner-service

- Update cloud automation tools  https://github.com/dynatrace-ace/cloud-automation-tools
--- Update endpoints and payloads to configure the project
--- Update endpoints to upload the resources 
--- Update endpoints to run a quality gate evaluation 
--- Run it as container (upload to dynatrace Ace dockerhub)

Update pipelines 
--- Update jenkins pipeline (docker) to run the new cloud automation tools
--- Update Gitlab (docker)

Update documentation
--- New implementation details and if there are any breaking changes from user perspective

Test 
--- End 2 end demos 
----- Quality gate jenkins
----- Quality gate Gitlab
----- Security gates

**Comment by kristofre** [comment]
FYI: branch with upgrades to keptn 0.19.1: https://github.com/Dynatrace/ace-box/blob/3c656dcbedf0bbc326223935013ac279123ff03a/user-skel/ansible/roles/keptn/tasks/main.yml#L41

**Comment by kristofre** [comment]
FYI: dynatrace-service 0.25 works with Keptn 1.0, however a new version (0.26) with some improvements will be released tomorrow

**Comment by kristofre** [comment]
FYI: cloud automation instances will start to get updated on DEV/SPRINT starting jan 9; prod will follow week of Jan 25

**Comment by drqc** [comment]
HI @eemrdog I updated the https://github.com/dynatrace-ace/cloud-automation-tools with the code from Keptn GitLab Runner in the dev branch (https://gitlab.com/dynatrace-ace/keptn-gitlab-runner) to have one single repo under GitHub that we can use for Cloud automation tools. (the previous CA tools are contain in the branch named `keptn update` since I won't be using those for now as it requires more changes to the current Gitlab pipeline and possibly the Jenkins pipeline).
I created a new docker image in the https://hub.docker.com/repository/docker/dynatraceace/cloud-automation-tools with the latest tag that contains the code from Keptn GitLab Runner with the  resource endpoint fixed.
 I also updated your branch 401-feature-update-to-keptn-1 with the updated image reference in gitlab (before it was dynatraceace/keptn-gitlab-runner:3.0 now it is dynatraceace/cloud-automation-tools:latest).
 Once the testing is done we need to update the latest tag to point to an specific docker release. 
In my current testing the pipeline works but there is an issue with an SLI expression that needs to be fixed. Once that is done the next one todo would be the jenkins pipeline

**Comment by eemrdog** [comment]
Gitlab and JEnkins tests are ok. The final thing we need to do is to update the cloud automation docker image version tag instead of "latest" tag. @drqc could you be able to provide the image tag and I can update it in the acebox accordingly?
