### ISSUE TITLE
[BUG] Keptn deployment seems to fail when deploying to Azure

### ISSUE THREAD

**Issue by lplichart** [Dynatrace/ace-box#416]
**Describe the bug**
I'm trying to run the ace-box deployment to Azure using terraform, but it fails at the task to deploy Keptn on a Kubernetes cluster

**To Reproduce**
1. az login to connect to Azure
2. run terraform with the minimal tfvars variables (azure region, DT tenant and token
3. See error:

module.provisioner.null_resource.provisioner_ace_enable (remote-exec): TASK [keptn : Deploy Keptn on Kubernetes cluster] ******************************
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [13m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [13m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [13m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [13m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [14m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [14m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [14m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [14m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [14m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [14m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [15m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [15m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [15m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [15m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [15m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [15m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [16m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [16m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [16m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [16m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [16m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [16m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [17m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [17m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [17m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [17m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [17m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [17m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [18m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [18m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [18m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [18m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [18m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [18m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [19m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [19m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [19m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [19m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [19m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [19m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [20m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [20m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [20m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [20m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [20m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [20m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [21m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [21m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [21m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [21m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [21m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [21m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [22m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [22m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [22m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [22m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [22m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [22m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [23m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [23m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [23m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [23m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [23m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [23m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [24m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [24m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [24m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [24m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [24m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [24m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [25m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [25m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [25m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [25m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [25m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [25m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [26m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [26m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [26m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [26m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [26m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [26m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [27m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [27m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [27m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [27m30s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [27m40s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [27m50s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [28m0s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [28m10s elapsed]
module.provisioner.null_resource.provisioner_ace_enable: Still creating... [28m20s elapsed]
module.provisioner.null_resource.provisioner_ace_enable (remote-exec): fatal: [localhost]: FAILED! => {"changed": false, "command": "/snap/bin/helm --version=1.0.0 upgrade -i --reset-values --wait --timeout 15m --create-namespace -f=/tmp/tmp03tbryry.yml keptn keptn/keptn", "msg": "Failure when executing Helm command. Exited 1.\nstdout: Release \"keptn\" does not exist. Installing it now.\n\nstderr: Error: timed out waiting for the condition\n", "stderr": "Error: timed out waiting for the condition\n", "stderr_lines": ["Error: timed out waiting for the condition"], "stdout": "Release \"keptn\" does not exist. Installing it now.\n", "stdout_lines": ["Release \"keptn\" does not exist. Installing it now."]}

module.provisioner.null_resource.provisioner_ace_enable (remote-exec): PLAY RECAP *********************************************************************
module.provisioner.null_resource.provisioner_ace_enable (remote-exec): localhost                  : ok=86   changed=39   unreachable=0    failed=1    skipped=13   rescued=0    ignored=0

module.provisioner.null_resource.provisioner_ace_enable (remote-exec): Traceback (most recent call last):
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/local/bin/ace", line 553, in <module>
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     ace(auto_envvar_prefix='ACE')
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     return self.main(*args, **kwargs)
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     rv = self.invoke(ctx)
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     return _process_result(sub_ctx.command.invoke(sub_ctx))
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     return ctx.invoke(self.callback, **ctx.params)
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     return __callback(*args, **kwargs)
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/local/bin/ace", line 489, in enable
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     subprocess.run((
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):   File "/usr/lib/python3.8/subprocess.py", line 516, in run
module.provisioner.null_resource.provisioner_ace_enable (remote-exec):     raise CalledProcessError(retcode, process.args,
module.provisioner.null_resource.provisioner_ace_enable (remote-exec): subprocess.CalledProcessError: Command 'ansible-playbook main-v2.yml --extra-vars "ace_box_user=ace" --tags "demo_default"' returned non-zero exit status 2.
╷
│ Error: remote-exec provisioner error
│
│   with module.provisioner.null_resource.provisioner_ace_enable,
│   on ../modules/ace-box-provisioner/main.tf line 132, in resource "null_resource" "provisioner_ace_enable":
│  132:   provisioner "remote-exec" {
│
│ error executing "/tmp/terraform_1011308388.sh": Process exited with status 1

**Expected behavior**
I expect the deployment to succeed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5
 - Browser; N/A

**Comment by kristofre** [comment]
@eemrdog can you work with Laurent on this? Could be that the standard VM size is insufficient.

**Comment by eemrdog** [comment]
Hi Laurent, can you try with the below instance type?
"Standard_A8m_v2" (with 8 vCPU) instead of the default "Standard_A4m_v2" (with 4 vCPU).

As I checked, we are using an instance type of 8 vCPU in default for gcloud. So, lets test the same for Azure.

**Comment by eemrdog** [comment]
The problem seems related to Azure persistent volume claims with the assigned rights for mongo db for Keptn V1.0.0 installation.
I asked for a solution to the keptn community slack channel, and depending on the response, we can move forward.

**Comment by tobigremmer-dt** [comment]
Perhaps related to: https://github.com/keptn/keptn/issues/9397

**Comment by eemrdog** [comment]
Updating the keptn-mongo deployment with both readiness and liveness probe timeoutSeconds: 15 worked fine in my tests.  
@lplichart , could you reapply the provisioning using the dev branch, updating the instance type with an 8 vCPU machine?  And then edit the keptn-mongo deployment with the above changes?

This can be a workaround solution for Azure-based deployments.

**Comment by eemrdog** [comment]
This is resolved by changing the Azure instance type from A type instances to B type instances as A type instances are not supported anymore. After testing with B8ms type instance, the deployment has been completed successfully. Therefore, the default instance type will be B8ms standard general purpose in terraform for Azure deployments.

![image](https://user-images.githubusercontent.com/53410643/215958059-1d0dcac2-c147-40e2-836b-d4187ec3efdd.png)
