### ISSUE TITLE
[BUG] Legacy HOT content

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#417]
**Describe the bug**
Currently, there are multiple roles that are not in use anymore. They shall be cleaned up:
- hot-appsec
- hot-monaco-gitops
- hot-quality-gates

**Comment by kristofre** [comment]
I believe the `hot-appsec` is still used and would need to be turned into an external repo.
@anton-freyberg can you confirm?

**Comment by anton-fre** [comment]
External repo already created. Not used as a built-in role anymore.
https://github.com/dynatrace-ace/ace-box-ext-hot-appsec
