### ISSUE TITLE
[BUG] k8s 1.23 nearly end of DT support

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#427]
**Describe the bug**
Following the support lifecycle of DT: https://www.dynatrace.com/support/help/technology-support/support-model-for-kubernetes

1.23 will no longer be supported from Feb 2023, we should upgrade to a supported version.
Additionally, we should also upgrade the DT operator to the recommended version

**Comment by tobigremmer-dt** [comment]
Duplicates #217
