### ISSUE TITLE
[BUG] Hide token for ansible playbooks logs

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#453]
**Describe the bug**
Currently token is being add as a query string parameter for playbooks. We need to check the playbooks for the internal and external use cases to fix this issue

**Comment by tobigremmer-dt** [comment]
Hi Diego, can you please be more explicit. What playbooks are you referring to? What token are you referring to?

**Comment by drqc** [comment]
yes, I was initially researching where we are using these tokens, seems that only on the autoremediation use case needs fixing. I see you created a bug for that one so I'm closing this one
