### ISSUE TITLE
[FEATURE] Explore git secrets hook to prevent commiting secrets

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#457]
Explore the functionality to use precommits to prevent leaking tokens

**Comment by drqc** [comment]
First option: Use Dynatrace version of AWS git secrets: https://bitbucket.lab.dynatrace.org/projects/SEC/repos/git-secrets/browse.
Observations:
- Requires access to the repo for each contributor or the need to upload this repo in a github repo. The initial installation is per developer machine. The final configuration once the command is install is with a single line.
- Sharing hooks require a configuration command.
- Exploration PR created 
- Validation for dyntrace tokens is based on a fix format

**Comment by tobigremmer-dt** [comment]
Quick update as discussed in our team call:
- pre-commit hook can be set up as an optional feature
- preferred is a solution that runs automatically on commits/PRs (Github actions)
- git-secrets is not public, cumbersome to setup and outdated, and should therefore not be used. GitGuardian is already enabled for our org and the preferred solution
