### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by kristofre** [Dynatrace/ace-box#49]
### Discussed in https://github.com/Dynatrace/ace-box/discussions/48

<div type='discussions-op-text'>

<sup>Originally posted by **kristofre** July 20, 2021</sup>
We should support https for all the supporting services.
Now that we support custom domains we can use proper Lets Encrypt certificates together with cert-manager.</div>

**Comment by tobigremmer-dt** [comment]
As there are a quotas around Lets Encrypt cert registrations and to align with DTU cert provisioning standards, certificates shall be provided by respective cloud providers.

Closing issue in favor of:
- #616 
- #617 
- #618
