### ISSUE TITLE
[BUG] Repo setup failures

### ISSUE THREAD

**Issue by robinwyss** [Dynatrace/ace-box#501]
**Describe the bug**
When using the role app-simplenode, the deployment fails with the following error message: 
`fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["git", "clone", "http://dynatrace:XYZ@http/://dynatrace:XYZ@10.152.183.194:3000/hot/appsec/demo/ace.git", "/home/ubuntu/repos/ace"], "delta": "0:00:00.030921", "end": "2023-06-22 09:03:47.504990", "msg": "non-zero return code", "rc": 128, "start": "2023-06-22 09:03:47.474069", "stderr": "Cloning into '/home/ubuntu/repos/ace'...\nfatal: unable to access 'http://http/://dynatrace:XYZ@10.152.183.194:3000/hot/appsec/demo/ace.git/': Could not resolve host: http", "stderr_lines": ["Cloning into '/home/ubuntu/repos/ace'...", "fatal: unable to access 'http://http/://dynatrace:XYZ@10.152.183.194:3000/hot/appsec/demo/ace.git/': Could not resolve host: http"], "stdout": "", "stdout_lines": []}`
It looks like the URL for the git repository is not assembled correctly, the http:// prefix is added twice: `http://http/://dynatrace:XYZ@10.152.183.194:3000/hot/appsec/demo/ace.git`

The issue is in the _Setup new repo_ step, as a workaround, line 36 in main.yml of the app-simplenode can be modified: 
Replace 
_ansible.builtin.command: "git clone https://{{ git_username }}:{{ git_password }}@{{ git_endpoint }}/{{ git_org_name }}/{{ repo_name }}.git {{ repo_src }}"_
by 
_ansible.builtin.command: "git clone {{ git_username }}:{{ git_password }}@{{ git_endpoint }}/{{ git_org_name }}/{{ repo_name }}.git {{ repo_src }}"_

Ace-Box v.1.16.0

**Comment by tobigremmer-dt** [comment]
Duplicates #502
