### ISSUE TITLE
[BUG] - Deployment Events not reaching Production Simplenodeservice

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#59]
**Describe the bug**
When running ACE-BOX demo pipelines, the pipelines work great and the events are showing up on the Staging SImplenodeservice.  However, the events are not arriving on the Production entity when the pipeline passes the evaluation and deploys to production.

**To Reproduce**
1. Run Demo Pipelines for build 1 or 3 so they complete all the way to production
2. Events will not appear on the simplenodeservice.production entity.

**Expected behavior**
A deployment event to arrive on the production simplenodeservice when the deployment to production ocurrs.

![simplenode-production](https://user-images.githubusercontent.com/52331581/127008174-dbe1de9d-f87a-4b7c-8690-36d5f49186e8.JPG)

**Comment by tobigremmer-dt** [comment]
~~Same issue in Staging:~~

```
Failed To post Dynatrace event:{"error":{"code":400,"message":"Invalid attachRules object provided. No entity IDs match: Matching rule: PushEventAttachRules{entityIds=null, tagRules=[TagMatchRule{meTypes=[PROCESS_GROUP_INSTANCE], tags=[[ENVIRONMENT]DT_APPLICATION_BUILD_VERSION:1.0.0-e23b79, [KUBERNETES]app.kubernetes.io/name:simplenodeservice, [KUBERNETES]app.kubernetes.io/part-of:simplenode-app, [KUBERNETES]app.kubernetes.io/component:api, [CONTEXTLESS]environment:staging]}]}"}}
```

Update: Nevermind, different issue.
