### ISSUE TITLE
[FEATURE] Alternate/Optional: Use a DT Dashboard to deliver SLI's and SLO's for Quality Gates demo

### ISSUE THREAD

**Issue by jpc-dt** [Dynatrace/ace-box#62]
Rather than only having yaml files for demo of Quality Gates, do we have the opportunity to use a Dashboard to demo the same functionality?  If not, would like to have one for customers who are concerned about scaling yaml file definitions.

**Comment by kristofre** [comment]
Agreed @jpc-dt, we need to incorporate that as part of the demo flow. At least it will make the initial onboarding a lot easier.

**Comment by tobigremmer-dt** [comment]
Was implemented in Jenkins / Not applicable for SRG.
