### ISSUE TITLE
[BUG] SRG GitLab Example - Mismatch in workflow query and biz event service and stage name

### ISSUE THREAD

**Issue by JasonOstroski** [Dynatrace/ace-box#631]
**Describe the bug**
This occurs when using the srg-pipeline in Gitlab. The biz event written to Dynatrace uses the naming of service = "simplenodeservice" and stage = "staging". However, the workflow that is looking for that event uses the naming of tag.service = "simplenodeservice" and tag.stage = "staging" (has tag. before it.) This causes the workflow to never get triggered and the pipeline to fail.

**To Reproduce**
Run the SRG-Pipeline in Gitlab.

**Additional context**
One fix is to update the monaco/srg/wf.json to remove the "tag." in front of the service and stage. Not sure if it's better to fix it in the biz event or the workflow. 

<img width="1293" alt="image" src="https://github.com/Dynatrace/ace-box/assets/22330658/de5074d4-0386-46ea-9bef-e8e52d0f1f44">

**Comment by tobigremmer-dt** [comment]
Hi @JasonOstroski , thanks for flagging! Can you create a PR with your changes?

**Comment by tobigremmer-dt** [comment]
Resolved in #636
