### ISSUE TITLE
[BUG] When installing the Jenkins role with k3s it shows an error

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#643]
When installing the Jenkins role in k3s using 

```
- include_role:
    name: jenkins
```

![image](https://github.com/Dynatrace/ace-box/assets/70604844/25d3d335-73fe-41d0-b936-3c8589ff1a58)

![image](https://github.com/Dynatrace/ace-box/assets/70604844/6f41338a-466c-47f3-96de-41c9a1aebba8)

**Comment by kristofre** [comment]
Resolved by https://github.com/Dynatrace/ace-box/pull/750
