### ISSUE TITLE
[BUG]  simplenode pipeline role fails without cloud automation information

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#644]
simplenode role pipeline fails since it's trying to execute a keptn init phase by default

![image](https://github.com/Dynatrace/ace-box/assets/70604844/db3c7cd0-3101-491a-8944-370f84df5752)

**Comment by tobigremmer-dt** [comment]
Which use case is this? Isn't that one of the deprecated ones?

**Comment by tobigremmer-dt** [comment]
@drqc See last comment

**Comment by kristofre** [comment]
@drqc can you provide the info above or close the issue please? `demo_all` provisions and works fine

**Comment by drqc** [comment]
no deprecated use case
