### ISSUE TITLE
[BUG] gitlab additional environments error in demo-ar-workflows-gitlab role

### ISSUE THREAD

**Issue by eemrdog** [Dynatrace/ace-box#662]
**Describe the bug**
module.provisioner.null_resource.provisioner_ace_enable (remote-exec): fatal: [localhost]: FAILED! => {"msg": "'gitlab_username' is undefined"}

**Comment by kristofre** [comment]
Is this one still there? I do not seem to be having this issue?

**Comment by eemrdog** [comment]
We can now close this issue since it hasn't occurred with the latest updates.
