### ISSUE TITLE
[BUG] Request timeouts - dynatrace Oauth endpoint degradation 

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#676]
Request are taking longer than the default 30 seconds set by ansible uri module in sprint tenants , this breaks provisioning when DT SSO endpoint degrades 
![image](https://github.com/user-attachments/assets/78d5cc31-611f-4b15-a921-1f1a2198bfa2)

Easy fix, extend timeout to 2 mins

**Comment by eemrdog** [comment]
It still randomly happens, so we can create retry and wait logic until it works as expected.

**Comment by drqc** [comment]
related issue added where one agent provisioning doesn't work k8s, timeout https://github.com/Dynatrace/ace-box/pull/683
