### ISSUE TITLE
Dynatrace Operator install failure[BUG] 

### ISSUE THREAD

**Issue by joshlange-dt** [Dynatrace/ace-box#70]
Intermittent issue on local windows provisioning with vagrant. DT operator install failure. See error below. Task failed on 3 consecutive provisions. 

![Ace-boxOperatorfailure](https://user-images.githubusercontent.com/56686007/130116755-d19eccf0-7d4c-4b51-a057-ec8594075734.png)

**Comment by alekseysirenko** [comment]
Hello folks, I am experiencing the same issue - not able to set up the Ace-Box for DVAs or customer demos. I am setting this up on my Dynatrace laptop, VPN disconnected, DNS set to Google DNS.

**Comment by luisr-escobar** [comment]
Seems to be failing on this [line](https://github.com/Dynatrace/dynatrace-operator/blob/master/deploy/install.sh#L105). The referenced link does a redirect so it could be linked to that somehow.

**Comment by kristofre** [comment]
@joshlange-dt @alekseysirenko I just merged a fix into master
