### ISSUE TITLE
[FEATURE] Provide real time output when running ace cli commands

### ISSUE THREAD

**Issue by dtu-engineering** [Dynatrace/ace-box#767]
### Overview
When some ace cli commands are executed (most importantly 'ace enable') the playbook output from the ansible execution is not provided until the end of the ace enable command. 

### DTU Implementation
DTU is executing the ace enable command and sending all output to a file like the example below. The ansible logs are all showing with the same timestamp as they are all being written at the same time at the end of the execution of the ace enable command. 

`ace enable https://"$GITHUB_USER":"$GITHUB_TOKEN"@"$ACEBOX_EXT_USE_CASE"@"$ACEBOX_EXT_USE_CASE_VERSION" 2>&1 | tee -a "$ACEBOX_LOG_FILE" `

This is leading to acebox logs provided via Aether deployments to all show the same timestamp.  We have verified the cloudwatch agent is forwarding logs with the correct timestamp if they are written to the monitored log file sequentially, vs. all at once. 

### Findings
I believe running the 'ace enable' command, or even ace prepare is not providing the real time output of the ansible playbook execution as this is being ran in a subprocess as seen below. All anisble output is provided only at the end of the execution of the ace enable command. 
 https://github.com/Dynatrace/ace-box/blob/dev/user-skel/.ace/ace#L494

I have found that it is possible to set a log file location via an ansible configuration file which does show timestamps of the ansible playbook execution, however this additionally adds extra text (process id, user, and some other values) to the log file making them less concise. I believe addressing the issue with the ace CLI commands is the best solution as there may be more ace CLI output that having accurate timestamps would benefit from as opposed to only the ansible execution.

**Comment by kristofre** [comment]
Thank you, @dtu-engineering team. Can you elaborate on "All anisble output is provided only at the end of the execution of the ace enable command"? When running on the command line, we get immediate output of each step and task execution as it happens.

**Comment by dtu-engineering** [comment]
@kristofre I was actually able to resolve this issue. After some additional testing I realized the way of testing was yielding a false result that made it appear the logs weren't available until the end of the execution when in fact they actually were as you mentioned.  

The issue was with the CloudWatch agent configuration, it had a setting to specify timestamp format to have it match the same format in CloudWatch when imported, however this causes all log entries without a timestamp to show the same exact time even though they were coming through real-time to the monitored log file. 

I will close this issue - All set!
