### ISSUE TITLE
[BUG] keptn tags not present on QG 

### ISSUE THREAD

**Issue by drqc** [Dynatrace/ace-box#80]
**Describe the bug**
Keptn quality gates is not working. Tags for keptn sli definition keptn_project, keptn_service,keptn_stage are not being included in Dynatrace entity. 

Initial fix:
Use the tags app, environment, stage in the sli.yaml

**Comment by tobigremmer-dt** [comment]
@drqc keptn_... tagging rules were created by Keptn's "dynatrace-service" by default. At one point this was changed to not create rules by default. Starting with https://github.com/Dynatrace/ace-box/pull/84 , DT release inventory tags are used instead of keptn_... .
