### ISSUE TITLE
[BUG] Custom Domains / HTTPS broken

### ISSUE THREAD

**Issue by tobigremmer-dt** [Dynatrace/ace-box#82]
**Describe the bug**
Jenkins can't checkout Gitea repositories anymore due to "server certificate verification failed".  Issue started occurring with a LetsEncrypt issued certificate around September 30.

Probably related: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

**Screenshots**

![image001](https://user-images.githubusercontent.com/83594825/136392457-bb8dc2d9-152d-4498-b39e-f3b3738d1a97.png)

**Comment by tobigremmer-dt** [comment]
Needs to be tested with latest Jenkins role.

**Comment by eemrdog** [comment]
This issue has not been encountered in the use cases that leverage Jenkins, so it can be closed. If we see the same problem, we can reopen it.
