### ISSUE TITLE
Keptn tags not properly applied when creating simplenodeservice build with Jenkins

### ISSUE THREAD

**Issue by lplichart** [Dynatrace/ace-box#85]
**Describe the bug**
When creating build number 1 in Jenkins with the ace-box, the build and deploy to staging steps get completed properly, but the test steps fails due to Keptn evaluation returning a score or 0.  When looking at the API call to retrieve the SLI metrics, it seems the call is filtering on tags that don't exist in the Dynatrace tenant:

keptn_project: simplenodeproject
keptn_stage: staging
keptn_service: simplenodeservice

**To Reproduce**
1. Go to 'Jenkins ace-demo' pipeline
2. Create build nr 1 (which is supposed to be successful)
3. Let the steps execute until 3. Test
4. See error in pipeline 3. Test at Keptn evaluation stage

**Expected behavior**
Build nr.1 should be successful, Keptn score should be higher than 0

**Screenshots**

![image](https://user-images.githubusercontent.com/32816942/138684802-bd002543-bd6a-48d8-85f4-39679964a038.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (ace-box runs on Ubuntu 18.04)
 - Browser: Chrome
 - Version: 94

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by tobigremmer-dt** [comment]
Hi @lplichart,

This issue was fixed with #81 and will be included in the next release. In the meantime, can you try to recreate your ACE-Box from the latest code on main?

Thanks,
Tobi

**Comment by lplichart** [comment]
Hi @tobigremmer-dt ,

indeed, everything is now fine.

Thanks
Laurent
