### ISSUE TITLE
[FEATURE] Add owner tags on cloud platforms

### ISSUE THREAD

**Issue by ghost** [Dynatrace/ace-box#94]
**Is your feature request related to a problem? Please describe.**
When multiple users spin up ACE boxes in the same project / account, it's hard to see (later) which is which.

**Describe the solution you'd like**
Add an AWS (+ other cloud platforms) tag for `owner` automatically.

**Comment by kristofre** [comment]
HI @Dynatrace-Adam-Gardner , a good feature, but not high on the prio list.
For now, I suggest using the `name_prefix` variable in `terraform.tfvars` and set it to something you recognise, e.g. your name.
