### ISSUE TITLE
[FEATURE] monaco-gitops-demo usecase needs better documentation

### ISSUE THREAD

**Issue by ghost** [Dynatrace/ace-box#95]
**Describe the bug**
Running ACE-Box in `demo` mode and trying to trigger `monaco-gitops-demo` I get:

```
+ git config user.name dynatrace
[Pipeline] sh
+ git checkout -B onboarding/
fatal: 'onboarding/' is not a valid branch name.
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 128
Finished: FAILURE
```

**To Reproduce**
1. Spin up ACE-Box in Demo mode
2. Go to Jenkins
3. Run the `monaco-gitops-demo` pipeline

**Comment by kristofre** [comment]
Hi @Dynatrace-Adam-Gardner , `monaco-gitops-demo` is not a pipeline, it is a folder.
Within that folder you have a pipeline called `Monaco - Application Onboarding` that should run fine.

**Comment by ghost** [comment]
Hi Kristof. You're right and it did work. But that pipeline doesn't apply the config. What's the next step?

If you and I could have a chat on the scenarios and workflows for the ACE box, I'll be happy to take on the task of improving documentation on the supported scenarios.

**Comment by kristofre** [comment]
Hi Adam,

please set up a call with me this week and I will demo this piece. You are correct though that documentation is lacking on how to showcase this poperly.

**Comment by kristofre** [comment]
@Dynatrace-Adam-Gardner I have opened a PR for this
