### ISSUE TITLE
[BUG] Timing: ace-demo fails no tags on service

### ISSUE THREAD

**Issue by ghost** [Dynatrace/ace-box#96]
**Describe the bug**
ace-demo pipeline build 1 fails on `3. Test` because Keptn quality gate has a score of zero.

A score of zero is recorded because some metrics return no data points. These metrics return no data points because the environment tags that the `sli.yaml` file relies upon are not present on the service level (although they are on the PG).

Waiting a few mins, the tags do appear so this is a timing issue.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/13639658/142809874-8ae11118-410a-4f29-8402-e0ae019056fe.png">

A few mins later...

<img width="557" alt="image" src="https://user-images.githubusercontent.com/13639658/142809891-d4d28bb3-a96c-441c-afdc-9568307586ea.png">

**Suggested Fix**

Either Use [Kubernetes] tags which seem to appear more quickly: `[Kubernetes]app.kubernetes.io/version: 1.0.0` etc. and / or wait for tags to appear before building and running quality gate.

**Comment by kristofre** [comment]
@Dynatrace-Adam-Gardner does this also impact a subsequent pipeline run? 
We might have to just increase a wait. Using Kubernetes tags is not possible as we rely on the build version here which can only be set using an env variable.

**Comment by kristofre** [comment]
This seems to only affect the first build and is caused by the delay between the simplenode process being started and monitored by the OneAgent and the service being detected and eventually the tags being propagated. Will fix by means of documentation as we don't want to slow down all subsequent builds
