### ISSUE TITLE
[FEATURE] Set ace MAC Staging dashboard preset to true

### ISSUE THREAD

**Issue by ghost** [Dynatrace/ace-box#98]
**Is your feature request related to a problem? Please describe.**
The dashboard does not have an owner so you need to toggle the "view all dashboards" switch. It's not immediately obvious (for someone who doesn't know the ace-box well) that a dashboard is even built (so they don't know to go looking).

**Describe the solution you'd like**
Set `preset: true` in the dashboard config so it

```
"dashboardMetadata": {
  "name": "{{ .name }}",
  "shared": true,
  "owner": "",
  "preset": true,
  ...
}
```

**Describe alternatives you've considered**
Setting the users email address as an owner

**Comment by tobigremmer-dt** [comment]
TBD:
- Clean up legacy dashboards such as "ACE Staging dashboard", "ACE dashboard", "ace-demo-canary..."
- Provide one dashboard per use case (quality gates, auto remediation)
- Add link to ACE-Box dashboard including credentials to each DT dashboard

**Comment by tobigremmer-dt** [comment]
MAC demo deprecated.
